{
 "title": "API metrics",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(gin_uri_request_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(uri) (rate(gin_uri_request_total{code!~\"[45][0-9]+\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "rate(gin_request_duration_sum[$__rate_interval]) / rate(gin_request_duration_count[$__rate_interval])"
    }
   ]
  }
 ]
}