{
 "title": "Docker container metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "container_name",
    "label": "Container name",
    "query": "SHOW TAG VALUES WITH KEY = \"container_name\""
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "container_name" ], "type": "tag" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$container_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "container_name" ], "type": "tag" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$container_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Disc read/write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_container_name: $col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" }
     ],
     "measurement": "docker_container_blkio",
     "select": [
      [
       {
        "params": [
         "io_service_bytes_recursive_write"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ "write" ], "type": "alias" }
      ],
      [
       {
        "params": [
         "io_service_bytes_recursive_read"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ "* -1" ], "type": "math" },
       { "params": [ "read" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$container_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Network in/out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_container_name: $col",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" }
     ],
     "measurement": "docker_container_net",
     "select": [
      [
       { "params": [ "rx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ "received" ], "type": "alias" }
      ],
      [
       { "params": [ "tx_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "derivative" },
       { "params": [ "* -1" ], "type": "math" },
       { "params": [ "sent" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "container_name", "operator": "=~", "value": "/^$container_name$/" }
     ]
    }
   ]
  }
 ]
}