drop table if exists public.users;

create table public.users(
    id integer primary key generated by default as identity,
    password varchar(255) not null,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    birthdate varchar(10) not null,
    gender varchar(255),
    interests text,
    city varchar(255)
);

drop index if exists users_first_last_names;

create index users_first_last_names on public.users (first_name varchar_pattern_ops, last_name varchar_pattern_ops);
