drop table if exists public.users;

create table public.users(
    id integer primary key generated by default as identity,
    password varchar(255) not null,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    birthdate varchar(10) not null,
    gender varchar(255),
    interests text,
    city varchar(255)
);
